### PR TITLE
[#225] Pass package revisions to fpm via --iteration

### PR DESCRIPTION
**Pull request by SwooshyCueb**
Addresses #225

### CODE REVIEW

**Comment by trel** [comment]
ah, nice.   all the knobs.

**Comment by SwooshyCueb** [comment]
Did a quick test with just the cmake package, I think this is ready for review.

**Review by korydraughn — APPROVED** [review]
Seems good. I didn't spot anything unusual.

**Comment by korydraughn** [comment]
Let's get one more approval before pounding.

**Review by alanking — APPROVED** [review]
\# it

**Comment by SwooshyCueb** [comment]
\#'d

**Pull request merged**
