### PR TITLE
[#259,#261] Remove EL7 support; normalize Boost builds between distros

### PR DESCRIPTION
**Pull request by SwooshyCueb**
Addresses #259
Addresses #261

This PR does a few things:
  - Removes EL7 support to make maintenance easier.
  - Ensures Boost.Iostreams is always built against all compression libraries it supports. (Previously this varied from distro to distro, resulting in oddities like EL8 supporting zstd compression while EL9 didn't.)
  - Explicitly builds Boost with C++20. (This requires the ugly `consteval` workaround for Clang 13.)
  - Explicitly disables building Boost.Regex and Boost.Locale against ICU when building against libc++. (ICU is a C++ library and therefore links to libstdc++.)
  - Explicitly enables building Boost.Regex and Boost.Locale against ICU when builidng against libstdc++.

Those using development environment containers to build externals will need to rebuild their containers once this is merged.

I've successfully built packages with these changes on all distros we support and everything seems normal. All the changes to the boost packages are supposedly binary-compatible with the *potential* exception of the explicit C++ standard. As such, I've only bumped the package revision for boost and boost-libcxx. Rebuilds of dependent packages should not be necessary. I'm going to double-check that there are no missing exported symbols compared to our previous release, though, so PR is in draft mode for now.

### CODE REVIEW

**Review by korydraughn — COMMENTED** [review]
Nothing unusual stands out to me.

Awaiting final results.

**Comment by SwooshyCueb** [comment]
There are some symbols removed from boost.locale, but most are for the icu backend, and since we don't currently link to boost.locale as far as I can tell, I think it's safe to mark this ready for review.

**Review by alanking — APPROVED** [review]
One of the commit messages says "Ensures Boost.Iostreams is always built against all compression compression libraries it supports" if you feel like fixing that up. Otherwise, looks good to me.

**Comment by SwooshyCueb** [comment]
> One of the commit messages says "Ensures Boost.Iostreams is always built against all compression compression libraries it supports" if you feel like fixing that up. Otherwise, looks good to me.

Fixed

**Review by alanking — COMMENTED** [review]
Seems good to me. Let's wait for another approval before we put this in, just in case.

**Review by korydraughn — APPROVED** [review]
Looks the same as last time.

Let's get it in if everything's working.

**Comment by SwooshyCueb** [comment]
\#'d

**Pull request merged**
