### PR TITLE
[irods/irods_5713] Bump nlohmann-json to 3.10.4, use CMake to build, switch to split headers, use proper include dir

### PR DESCRIPTION
**Pull request by SwooshyCueb**

### CODE REVIEW

**Comment by trel** [comment]
just for posterity... why build instead of just include the header(s)?

**Comment by SwooshyCueb** [comment]
Building generates cmake and pkg-config configuration files.

**Comment by trel** [comment]
oh, right, the actual issue explains all that - sorry.   yes, please # it.

**Comment by SwooshyCueb** [comment]
\#'d

**Pull request merged**
