### PR TITLE
[irods/libs3#24] Referring to the new libs library. (main)

### PR DESCRIPTION
**Pull request by JustinKyleJames**

### CODE REVIEW

**Comment by trel** [comment]
commit message needs more 3 in libs3

**Comment by alanking** [comment]
We recently bumped the libs3 externals SHA to fix a separate issue. This is bumping the SHA to fix the linked issue, and it looks like we are going to be applying the change to at least 4.2.12.1: https://github.com/irods/irods_resource_plugin_s3/issues/2104

**Review by korydraughn — APPROVED** [review]

**Review by alanking — COMMENTED** [review]
As @trel pointed out, let's fix up the commit message and we can get this in:

Referring to the new libs library.

...should be...

Referring to the new libs3 library.

**Review by alanking — APPROVED** [review]
Fixed commit message :)

Any last thoughts?

**Review by korydraughn — APPROVED** [review]
None from me. Let's do it.

**Pull request merged**
