### PR TITLE
[#174,#175] Set RPATH for qpid-proton and explicitly disable linking against jsoncpp

### LINKED ISSUE #174: RPATH/RUNPATH not set in qpid-proton libraries
The qpid-proton libraries do not have their `RPATH`/`RUNPATH` set. This causes problems when linking against `libqpid-proton-cpp` and friends.

### LINKED ISSUE #175: qpid-proton build fails when jsoncpp is present
qpid-proton will try to link against jsoncpp by default if it is detected by CMake at build-time. Since we do not provide a libc++-linked jsoncpp, CMake is likely to pick up libstdc++-linked jsoncpp, which will cause linking to fail.

### PR DESCRIPTION
**Pull request by SwooshyCueb**
Closes #174 
Closes #175

### CODE REVIEW

**Comment by korydraughn** [comment]
Changes look good.

Waiting for your signal that the changes produce the expected results.

**Comment by trel** [comment]
initial eyeballing looks good to me too.

consider breaking jsoncpp into separate commit?   unless they're related/required to be together.

**Comment by SwooshyCueb** [comment]
> Waiting for your signal that the changes produce the expected results.

As far as I can tell, it does what it's supposed to. `readelf -d` shows the `RPATH` as expected

> consider breaking jsoncpp into separate commit? unless they're related/required to be together.

Done

**Comment by korydraughn** [comment]
If you're happy with the changes, let's add the issue numbers and get it merged.

**Comment by SwooshyCueb** [comment]
\#'d

**Review by trel — APPROVED** [review]

**Review by korydraughn — APPROVED** [review]

**Comment by SwooshyCueb** [comment]
Who needs to be poked to get this merged?

**Comment by korydraughn** [comment]
@alanking ping

**Review by alanking — APPROVED** [review]
Found another repo I'm not watching...

**Pull request merged**
