### PR TITLE
[#260] Fix invalid escape sequences in clang package's python files

### PR DESCRIPTION
**Pull request by SwooshyCueb**
Addresses #260

Not yet tested, so PR is in draft mode

### CODE REVIEW

**Review by korydraughn — COMMENTED** [review]
Looks good to me.

Awaiting results of testing.

**Comment by SwooshyCueb** [comment]
Testing revealed no surprises, marking ready for review

**Review by korydraughn — APPROVED** [review]
Let's get one more approval before pounding it.

**Review by alanking — APPROVED** [review]
\# it

**Comment by SwooshyCueb** [comment]
\#'d

@trel New packages are in bison

**Comment by trel** [comment]
got it - thanks

**Pull request merged**
