### PR TITLE
[irods/irods#6039] Added support for Rocky Linux 8 (main)

### PR DESCRIPTION
**Pull request by korydraughn**

### CODE REVIEW

**Comment by trel** [comment]
is that all it took?    otherwise identical/functioning like alma linux?    that's great if true.

**Comment by korydraughn** [comment]
yes. all that is left is to update mungefs and irods/irods.

i'm verifying externals instructions work now. once complete, i'll only need to verify the package deps for irods/irods are correct.

**Comment by trel** [comment]
nice.

**Comment by korydraughn** [comment]
Added #

**Pull request merged**
