### PR TITLE
modified for centos 8.4 and rocky linux 8.4

### PR DESCRIPTION
**Pull request by peggy0135**
just modified the script for centos8.4 and rocky linux 8.4
Thank you

### CODE REVIEW

**Comment by peggy0135** [comment]
just modified the script for CentOS 8.4 and RockyLinux 8.4
including install_prerequisites.py, build.py
Thank you

**Comment by peggy0135** [comment]
just modified the script for CentOS 8.4 and RockyLinux 8.4
including install_prerequisites.py, build.py
Thank you

**Comment by peggy0135** [comment]
fixed my mistakes in the commands
sorry

**Comment by peggy0135** [comment]
add a dependency will be needed when building "iRODS"

**Comment by trel** [comment]
we've now got this working since f39d262f34e7ed8a8c04aa7a765f499cf463bb38 and 2fa226fa242b7b5a9561b22a792eed0ece2e69bd

**Comment by trel** [comment]
Thank you @peggy0135 - this was helpful.

**Pull request closed without merging**
