### PR TITLE
Build without installing fpm.

### PR DESCRIPTION
**Pull request by NickHastings**
Hi,

prompted by discussion at https://github.com/irods/irods/issues/5082 I attempted to follow
https://docs.irods.org/4.2.8/getting_started/installation/#non-package-install-run-in-place
to perform a build that does not use fpm. I discovered that the build scripts still try to install
fpm and related ruby packages (even though they are not used). This somewhat defeats the
purpose of doing the build in this manner. This branch contains some small changes to remove 
these dependencies in the case of this type of build.

The install procedure changes from:
```
user@hostname:/tmp/irods-externals $ ./install_prerequisites.py
user@hostname:/tmp/irods-externals $ make
```
to:
```
user@hostname:/tmp/irods-externals $ ./install_prerequisites.py -n
user@hostname:/tmp/irods-externals $ make NATIVE_PACKAGE=-n
```
Cheers,

Nick.

### CODE REVIEW

**Comment by trel** [comment]
Thanks!

**Comment by NickHastings** [comment]
Commit 6f2d486 was made because while working on this package I found that make would fail if clang-runtime had already been built.

**Comment by trel** [comment]
I have successfully run `make server NATIVE_PACKAGE=-n` (only building externals needed for the irods-server).

The externals only necessary for particular plugins had some other issues (#96), but I believe they're unrelated to this do-no-packaging effort.  The major downside of this approach is that because there are no package files being created... and the package files *are* the `make` targets... everything gets rebuilt on running `make` again.

**Comment by trel** [comment]
Minor, and we could always change it later...   Why the phrase `NATIVE_PACKAGE`?  

I found myself thinking that the python option should grow an 's'... `-p/--packages` and `-n/--no-packages` into dest='packages' with `default=True`.

Then the `make` environment variable might be better named... `SKIP_PACKAGING=1` or `SKIP_PACKAGING=true`.... or maybe just `PACKAGES` with a default of `-p`.

**Comment by NickHastings** [comment]
> Minor, and we could always change it later... Why the phrase `NATIVE_PACKAGE`?

Good question. I think the various dependencies are referred to as packages already so I wanted to somehow differentiate between the various "packages" and the system/native deb/rpm packages.
 
> I found myself thinking that the python option should grow an 's'... `-p/--packages` and `-n/--no-packages` into dest='packages' with `default=True`.
> 
> Then the `make` environment variable might be better named... `SKIP_PACKAGING=1` or `SKIP_PACKAGING=true`.... or maybe just `PACKAGES` with a default of `-p`.

I'm really not fussed about what the option is called, I can change it to what ever you like and push the changes to this branch.

On a slight side note I wonder if it is better to replace VERBOSE in the Makefile with a more general variable such as BUILD_OPTS then each target could change from:
```
$(FOO_PACKAGE) :
	./build.py $(VERBOSITY) ${NATIVE_PACKAGE} foo > foo.log 2>&1
```
to
```
$(FOO_PACKAGE) :
	./build.py $(BUILD_OPTS) foo > foo.log 2>&1
```

And then the user can set BUILD_OPTS to whatever they want. In practice this is no different to just reverting to how the Makefile is in the master branch but renaming the VERBOSE variable to BUILD_OPTS for clarity.

**Comment by trel** [comment]
I do like your `BUILD_OPTIONS` suggestion (we have a strong preference for using all the letters :) ).

Let's do that - can you update this PR with that?   and we're good to go.

**Comment by NickHastings** [comment]
> I do like your `BUILD_OPTIONS` suggestion (we have a strong preference for using all the letters :) ).
> 
> Let's do that - can you update this PR with that? and we're good to go.

Done.

**Comment by trel** [comment]
fixed a couple typos.   merging.   thanks!

**Pull request merged**
