### PR TITLE
[irods/irods_capability_indexing#128] Remove elasticlient and CPR

### PR DESCRIPTION
**Pull request by SwooshyCueb**
We are removing elasticlient and CPR for the reasons detailed here: irods/irods_capability_indexing#128

Once I've confirmed everything still builds just fine, I'll mark as ready for review.

### CODE REVIEW

**Comment by SwooshyCueb** [comment]
If there are no objections, I will \#

**Review by alanking — COMMENTED** [review]
My only concern here is being able to release indexing with 4.3.1. Does everything still work, or is it just a matter of building? Might be worth running tests to make sure (perhaps can enlist @d-w-moore)

**Comment by SwooshyCueb** [comment]
I can't get indexing to build at all for some distros, due to libcurl

**Comment by SwooshyCueb** [comment]
\#'d

**Review by alanking — APPROVED** [review]

**Pull request merged**
